# Generated by Django 5.2 on 2025-06-09 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('idSquare', models.AutoField(primary_key=True, serialize=False)),
                ('nameSquare', models.CharField(max_length=100)),
                ('colorSquare', models.CharField(blank=True, max_length=45, null=True)),
                ('widthSquare', models.IntegerField(blank=True, null=True)),
                ('heightSquare', models.IntegerField(blank=True, null=True)),
                ('descriptionSquare', models.TextField(blank=True, null=True)),
                ('effectDescription', models.TextField(blank=True, null=True)),
                ('typeSquare', models.CharField(blank=True, max_length=45, null=True)),
                ('imageSquare', models.TextField(blank=True, null=True)),
                ('worthSquare', models.IntegerField(blank=True, null=True)),
                ('currentUsageSquare', models.IntegerField(blank=True, null=True)),
                ('maxUsageSquare', models.IntegerField(blank=True, null=True)),
                ('tagSquare', models.CharField(blank=True, max_length=45, null=True)),
                ('damage1Square', models.CharField(blank=True, max_length=10, null=True)),
                ('damage2Square', models.CharField(blank=True, max_length=10, null=True)),
                ('valueArmorSquare', models.IntegerField(blank=True, null=True)),
                ('conditionEffectSquare', models.CharField(blank=True, max_length=100, null=True)),
                ('usageTypeSquare', models.CharField(blank=True, max_length=45, null=True)),
                ('isMagical', models.BooleanField(default=False)),
                ('pesoSquare', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Square',
            },
        ),
    ]
