# Generated by Django 5.2 on 2025-06-23 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameCharacter', models.CharField(blank=True, max_length=45, null=True)),
                ('backgroundCharacter', models.CharField(blank=True, max_length=45, null=True)),
                ('birthsignCharacter', models.CharField(blank=True, max_length=45, null=True)),
                ('coatCharacter', models.CharField(blank=True, max_length=45, null=True)),
                ('lookCharacter', models.CharField(blank=True, max_length=45, null=True)),
                ('strCurrentCharacter', models.IntegerField(blank=True, null=True)),
                ('dexCurrentCharacter', models.IntegerField(blank=True, null=True)),
                ('willCurrentCharacter', models.IntegerField(blank=True, null=True)),
                ('strMaxCharacter', models.IntegerField(blank=True, null=True)),
                ('dexMaxCharacter', models.IntegerField(blank=True, null=True)),
                ('willMaxCharacter', models.IntegerField(blank=True, null=True)),
                ('hpCurrentCharacter', models.IntegerField(blank=True, null=True)),
                ('hpMaxCharacter', models.IntegerField(blank=True, null=True)),
                ('pipsCharacter', models.IntegerField(blank=True, null=True)),
                ('levelCharacter', models.IntegerField(blank=True, null=True)),
                ('xpCharacter', models.IntegerField(blank=True, null=True)),
                ('gritCharacter', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_sheets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
