# Generated by Django 5.2 on 2025-06-16 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_item_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('currentUsageSquare', models.IntegerField(blank=True, null=True)),
                ('item_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_instances', to='app.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Item do Usuário',
                'verbose_name_plural': 'Itens do Usuário',
            },
        ),
    ]
