# Generated by Django 5.2 on 2025-06-23 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_charactersheet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useritem',
            options={'verbose_name': 'Item do Personagem', 'verbose_name_plural': 'Itens dos Personagens'},
        ),
        migrations.RemoveField(
            model_name='useritem',
            name='user',
        ),
        migrations.AddField(
            model_name='useritem',
            name='character_sheet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='app.charactersheet'),
            preserve_default=False,
        ),
    ]
