# Generated by Django 5.2 on 2025-06-24 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_useritem_options_remove_useritem_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactersheet',
            name='UrlImageCharacter',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
