# Generated by Django 5.2 on 2025-06-16 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_useritem'),
    ]

    operations = [
        migrations.AddField(
            model_name='useritem',
            name='PositionX',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useritem',
            name='PositionY',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
