# Generated by Django 5.2 on 2025-06-27 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_charactersheet_urlimagecharacter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterModelOptions(
            name='useritem',
            options={},
        ),
        migrations.AlterModelTable(
            name='useritem',
            table='User',
        ),
    ]
